### ISSUE TITLE
Tidy up repository

### ISSUE THREAD

**Issue by buck06191** [buck06191/BayesCMD#10]
Tidy up repository and remove any project specific folders - this repository should be as general as possible.

**Comment by buck06191** [comment]
## TODO ##

- [ ] Create `scripts/`directory.
- [ ] Move `single_run/`, `steady_state/`, `results_processing/`, `legion_scripts/` and `batch_Bayes/` to `scripts/`
- [ ] Move `batch.py` into `bayescmd/`
- [ ] Add `README.md` files to directories to  add explanation.
- [ ] Remove `.ipynb_checkpoints/`, `todo_notes/` and `testing/`
- [ ] Clean up `data/`
- [ ] Move `PLOS_paper/` to a new repository.
